@startuml

'=============== Produto ============'
class Iphone{
  + id: Integer
  + preco: Double
  + descricao:String
}
class Modelo{
  + id :Integer
  + nome String
}
enum Cor{
  + id: Integer: id
  + nomeCor: String
}
class Estoque{
  + id : Integer
  + quantidade: Integer

}
class entradaEstoque{
  + id: Integer
  + modelo: String
  + cor: String

}
Iphone "*" o--> "1" Cor
Iphone "*" *-->"1" Modelo
Iphone "1" o-->"1" Estoque
Estoque "1"<--*"*" entradaEstoque
'=============== Usuario ============'
class Usuario{
  + id: Integer
  + nome: String
  + cpf: String
  + dataNasciento: Date

}
class Telefone{
  + id:Integer
  + codigoArea: String
  + numero: String
}
enum Genero{
  +id: Integer
  + sexo: String
}
class Endereco{
  + id:Integer
  + cep: String
  + endereco: String
  + numero: Integer
  + complemento: String
}
'Guardar hash do cv do cartao'
'Hash da data de vencimento'
class Cartao{
  + numeroCartão: String
  + dataVencimento: String
  + cvDoCartão: String
}

Enum Funcao{
 + id: Integer
 + funcaoCartão: String
}

Usuario "*" o-->"1" Genero
Usuario "1"*-->"1" Telefone
Usuario "1" o-->"*" Endereco
Usuario "1" *-->"*" Cartao
Cartao "1" o-->"*" Funcao
'=============== Compra ============'
class ItemVenda{
  + itemVenda: List
}
class Venda{
  + id: Integer
  + relatorio: String
}
abstract class  Pagamento<abstract>{
  + dataHora: Date
}
class Pix {
  + ListaPix: List<Chave>
}
class Chave{
  + chavePix: String
}
Enum TipoChave{
  + id: Integer
  + chave :String
}

Enum CartaoCreditoDebito{
  + id : Integer
  + funcaoCartao: String
}


ItemVenda "1" o--> "*" Iphone
Venda "1"*-->"1" ItemVenda
Venda "*"--o "1" Usuario
Venda "1"--"1" Pagamento
Pagamento "1"--|>"1" Pix
Pagamento "1"--|>"1" CartaoCreditoDebito
Pix "1"--"*" Chave
Chave "1"-->"1" TipoChave

'=============== relacionamentos ============'
'Buscar os dados de enderço via api dos correios'

@enduml